// DEFINITIONS DES COMMANDES CLIENT ET REPONSES DU SERVEUR TERMINOA
//
// (d)2006 David.Romeuf@univ-lyon1.fr
//

#ifndef _CMDREP_TERMINOA

#define _CMDREP_TERMINOA

#include <qstring.h>

// Liste des commandes du client au serveur TERMINOA
//
#define NB_CMD_CLIENT_TERMINOA		28	// On compte aussi la derniere chaine vide

#define TERMINOA_CMD_SESAMEOUVRETOI	0
#define TERMINOA_CMD_EN_ATTENTE		1
#define TERMINOA_CMD_ARRET			2
#define TERMINOA_CMD_DECONNEXION	3
#define TERMINOA_CMD_AFFICHER		4
#define TERMINOA_CMD_MODE_IC		5
#define TERMINOA_CMD_MODE_DIAPO		6
#define TERMINOA_CMD_ECH_LIN		7
#define TERMINOA_CMD_ECH_LOG		8
#define TERMINOA_CMD_PAL_NB			9
#define TERMINOA_CMD_PAL_HALPHA		10
#define TERMINOA_CMD_PAL_NOB		11
#define TERMINOA_CMD_PAL_NVB		12
#define TERMINOA_CMD_PAL_NBB		13
#define TERMINOA_CMD_Z0				14
#define TERMINOA_CMD_Z1				15
#define TERMINOA_CMD_Z2				16
#define TERMINOA_CMD_Z3				17
#define TERMINOA_CMD_Z4				18
#define TERMINOA_CMD_Z5				19
#define TERMINOA_CMD_Z6				20
#define TERMINOA_CMD_Z7				21
#define TERMINOA_CMD_Z8				22
#define TERMINOA_CMD_Z9				23
#define TERMINOA_CMD_CSB			24
#define TERMINOA_CMD_CSH			25
#define TERMINOA_CMD_CPUILUT		26

static QString ListeCmdClientTerminOA[NB_CMD_CLIENT_TERMINOA]=
{
	"dYj{2bhehz3%514bmokczenn$$$$54$2jhbsj@Jdbz[dj~nd&dnk##dn",
	"<EN-ATTENTE?>",
	"<ARRET-SERVEUR-TERMINOA>",
	"<DECONNEXION>",
	"<AFFICHER>",
	"<MODE-IMAGE-COURANTE>",
	"<MODE-DIAPORAMA>",
	"<MODE-ECHELLE-LIN>",
	"<MODE-ECHELLE-LOG>",
	"<MODE-PALETTE-NB>",
	"<MODE-PALETTE-HALPHA>",
	"<MODE-PALETTE-NOIR-ORANGE-BLANC>",
	"<MODE-PALETTE-NOIR-VERT-BLANC>",
	"<MODE-PALETTE-NOIR-BLEU-BLANC>",
	"<VISU-Z0>",
	"<VISU-Z1>",
	"<VISU-Z2>",
	"<VISU-Z3>",
	"<VISU-Z4>",
	"<VISU-Z5>",
	"<VISU-Z6>",
	"<VISU-Z7>",
	"<VISU-Z8>",
	"<VISU-Z9>",
	"<CONS-SEUIL-BAS>",
	"<CONS-SEUIL-HAUT>",
	"<CONS-PUI-LUT>",
	""
};

// Liste des reponses du serveur TERMINOA au client
//
#define NB_REP_SERVEUR_TERMINOA			31	// On compte aussi la derniere chaine vide

#define TERMINOA_REP_CMD_INCONNUE		0
#define TERMINOA_REP_EN_ATTENTE			1
#define TERMINOA_REP_OK_AFFICHER		2
#define TERMINOA_REP_NONOK_AFFICHER		3
#define TERMINOA_REP_OK_MODE_IC			4
#define TERMINOA_REP_OK_MODE_DIAPO		5
#define TERMINOA_REP_OK_ECH_LIN			6
#define TERMINOA_REP_OK_ECH_LOG			7
#define TERMINOA_REP_OK_PAL_NB			8
#define TERMINOA_REP_OK_PAL_HALPHA		9
#define TERMINOA_REP_OK_PAL_NOB			10
#define TERMINOA_REP_OK_PAL_NVB			11
#define TERMINOA_REP_OK_PAL_NBB			12
#define TERMINOA_REP_OK_Z0				13
#define TERMINOA_REP_OK_Z1				14
#define TERMINOA_REP_OK_Z2				15
#define TERMINOA_REP_OK_Z3				16
#define TERMINOA_REP_OK_Z4				17
#define TERMINOA_REP_OK_Z5				18
#define TERMINOA_REP_OK_Z6				19
#define TERMINOA_REP_OK_Z7				20
#define TERMINOA_REP_OK_Z8				21
#define TERMINOA_REP_OK_Z9				22
#define TERMINOA_REP_OK_CSB				23
#define TERMINOA_REP_NONOK_CSB			24
#define TERMINOA_REP_OK_CSH				25
#define TERMINOA_REP_NONOK_CSH			26
#define TERMINOA_REP_OK_CPUILUT			27
#define TERMINOA_REP_NONOK_CPUILUT		28
#define TERMINOA_REP_OK_IMG_RECUE		29

static QString ListeRepServeurTerminOA[NB_REP_SERVEUR_TERMINOA]=
{
	"[<?>]",
	"[<TERMINOA-EN-ATTENTE>]",
	"[<TERMINOA-OK-AFFICHER>]",
	"[<TERMINOA-NONOK-AFFICHER>]",
	"[<TERMINOA-OK-MODE-IC>]",
	"[<TERMINOA-OK-MODE-DIAPO>]",
	"[<TERMINOA-OK-ECH-LIN>]",
	"[<TERMINOA-OK-ECH-LOG>]",
	"[<TERMINOA-OK-PAL-NB>]",
	"[<TERMINOA-OK-PAL-HALPHA>]",
	"[<TERMINOA-OK-PAL-NOIR-ORANGE-BLANC>]",
	"[<TERMINOA-OK-PAL-NOIR-VERT-BLANC>]",
	"[<TERMINOA-OK-PAL-NOIR-BLEU-BLANC>]",
	"[<TERMINOA-OK-Z0>]",
	"[<TERMINOA-OK-Z1>]",
	"[<TERMINOA-OK-Z2>]",
	"[<TERMINOA-OK-Z3>]",
	"[<TERMINOA-OK-Z4>]",
	"[<TERMINOA-OK-Z5>]",
	"[<TERMINOA-OK-Z6>]",
	"[<TERMINOA-OK-Z7>]",
	"[<TERMINOA-OK-Z8>]",
	"[<TERMINOA-OK-Z9>]",
	"[<TERMINOA-OK-CSB>]",
	"[<TERMINOA-NONOK-CSB>]",
	"[<TERMINOA-OK-CSH>]",
	"[<TERMINOA-NONOK-CSH>]",
	"[<TERMINOA-OK-CPUILUT>]",
	"[<TERMINOA-NONOK-CPUILUT>]",
	"[<TERMINOA-OK-IMG-RECUE>]",
	""
};

#endif

